attribute placement_force of \`$INSTANCE_NAME`:BSPIS:`$SiliconRevisionReplacementString`:SPISlave:`$VerilogSectionReplacementString`:Dp:u0\ : label is "U(2,5)";
attribute placement_force of \`$INSTANCE_NAME`:BSPIS:`$SiliconRevisionReplacementString`:SPISlave:RxStsReg\ : label is "U(3,5)";
attribute placement_force of \`$INSTANCE_NAME`:BSPIS:`$SiliconRevisionReplacementString`:SPISlave:BitCounter\ : label is "U(2,5)";
attribute placement_force of \`$INSTANCE_NAME`:BSPIS:`$SiliconRevisionReplacementString`:SPISlave:TxStsReg\ : label is "U(3,4)";
attribute placement_force of \`$INSTANCE_NAME`:BSPIS:`$SiliconRevisionReplacementString`:SPISlave:tx_load\ : signal is "U(2,5,B)3";
attribute placement_force of \`$INSTANCE_NAME`:BSPIS:`$SiliconRevisionReplacementString`:SPISlave:mosi_buf_overrun\ : signal is "U(2,5,B)2";
attribute placement_force of \`$INSTANCE_NAME`:BSPIS:`$SiliconRevisionReplacementString`:SPISlave:dpcounter_one\ : signal is "U(2,5,B)1";
attribute placement_force of \`$INSTANCE_NAME`:BSPIS:`$SiliconRevisionReplacementString`:SPISlave:mosi_to_dp\ : signal is "U(2,5,B)0";
attribute placement_force of \`$INSTANCE_NAME`:BSPIS:`$SiliconRevisionReplacementString`:SPISlave:tx_status_0\ : signal is "U(3,5,B)0";
attribute placement_force of \`$INSTANCE_NAME`:BSPIS:`$SiliconRevisionReplacementString`:SPISlave:mosi_tmp\ : signal is "U(3,5,B)1";
attribute placement_force of \`$INSTANCE_NAME`:BSPIS:`$SiliconRevisionReplacementString`:SPISlave:inv_ss\ : signal is "U(3,5,B)2";
attribute placement_force of \`$INSTANCE_NAME`:BSPIS:`$SiliconRevisionReplacementString`:SPISlave:rx_status_4\ : signal is "U(3,5,B)3";
attribute placement_force of \`$INSTANCE_NAME`:BSPIS:`$SiliconRevisionReplacementString`:SPISlave:sync_1\: label is "U(2,4)0";
attribute placement_force of \`$INSTANCE_NAME`:BSPIS:`$SiliconRevisionReplacementString`:SPISlave:sync_2\: label is "U(2,4)1";
attribute placement_force of \`$INSTANCE_NAME`:BSPIS:`$SiliconRevisionReplacementString`:SPISlave:sync_3\: label is "U(2,4)2";
attribute placement_force of \`$INSTANCE_NAME`:BSPIS:`$SiliconRevisionReplacementString`:SPISlave:sync_4\: label is "U(2,4)3";