//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRC_UART_v1_0.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CRC_UART_v0_1.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N should be in range [1, 64].
        /// </summary>
        internal static string ERROR_N_RANGE {
            get {
                return ResourceManager.GetString("ERROR_N_RANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Single Cycle implementation should be selected for Resolution less than 9.
        /// </summary>
        internal static string MSG_DISABLE_TIME_MULTIPLEXING {
            get {
                return ResourceManager.GetString("MSG_DISABLE_TIME_MULTIPLEXING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Time Division Multiplex implementation should be selected for Resolution greater than 32.
        /// </summary>
        internal static string MSG_ENABLE_TIME_MULTIPLEXING {
            get {
                return ResourceManager.GetString("MSG_ENABLE_TIME_MULTIPLEXING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Polynomial value.
        /// </summary>
        internal static string MSG_INVALID_POLYNOMIAL_VALUE {
            get {
                return ResourceManager.GetString("MSG_INVALID_POLYNOMIAL_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Seed value.
        /// </summary>
        internal static string MSG_INVALID_SEED_VALUE {
            get {
                return ResourceManager.GetString("MSG_INVALID_SEED_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum valid Seed value for N={0} is 0x{1}.
        /// </summary>
        internal static string MSG_MAX_VALID_SEED_VALUE {
            get {
                return ResourceManager.GetString("MSG_MAX_VALID_SEED_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem with parameters initialization..
        /// </summary>
        internal static string MSG_PARAMETER_INITIALIZATION {
            get {
                return ResourceManager.GetString("MSG_PARAMETER_INITIALIZATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polynomial value should be greater than zero.
        /// </summary>
        internal static string MSG_POLYNOMIAL_SHOULD_BE_GREATER_ZERO {
            get {
                return ResourceManager.GetString("MSG_POLYNOMIAL_SHOULD_BE_GREATER_ZERO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        internal static string PAGE_TITLE_ADVANCED {
            get {
                return ResourceManager.GetString("PAGE_TITLE_ADVANCED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Built-in.
        /// </summary>
        internal static string PAGE_TITLE_BUILTIN {
            get {
                return ResourceManager.GetString("PAGE_TITLE_BUILTIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polynomial.
        /// </summary>
        internal static string PAGE_TITLE_POLYNOMIAL {
            get {
                return ResourceManager.GetString("PAGE_TITLE_POLYNOMIAL", resourceCulture);
            }
        }
    }
}
